### ISSUE TITLE
Offline persistence

### ISSUE THREAD

**Issue by ZenithCode** [dkrprasetya/simple-firebase-csharp#4]
Hey,

Is there any way to turn on offline persistence in this plugin?

Thanks.

**Comment by ZenithCode** [comment]
This: https://firebase.google.com/docs/database/android/offline-capabilities

**Comment by tkesgar** [comment]
As far as I know, the plugin works with REST API, which doesn't have offline capabilities.

**Comment by ZenithCode** [comment]
Is this plugin built over their Android package? It should be available somewhere there if its mentioned in documentation.

Thanks.

**Comment by dkrprasetya** [comment]
No it is not. Since this only uses REST API on every requests I thought there's no need to built it based on the official Android Package. I will update the ReadMe later to make it clear.

There is no "offline capabilities", but we could do the trick by utilizing OnFailed listener on the REST calls to make it behaves as if it has "offline capabilities". Maybe I will take this idea for the next update, the implemented _FirebaseQueue_ and _FirebaseObserver_ could be modified so that it will have an option to act as if it has "offline capabilities".

Thanks for the suggestions!

**Comment by ZenithCode** [comment]
Thanks @dkrprasetya 

Keep it up! :-)
