### ISSUE TITLE
Failed Queue Pushes are still cleared from queue

### ISSUE THREAD

**Issue by ZenithCode** [dkrprasetya/simple-firebase-csharp#7]
Hi,

I've been testing this plugin but I found an issue with the queue.

If you lost internet and the Push failed, I get an error saying that Firebase is unable to resolve host but even though this happens, **_the message is still cleared from the queue._**

Shouldn't it be kept  it the queue until it is successfully sent (or app is quit)?
Regards,

**Comment by dkrprasetya** [comment]
Ah, yes. I haven't considered the offline persistence or whatsoever when I implemented that one. The current FirebaseQueue was only intended to provide a simple implementation to make the requests sent in order rather than being sent asynchronously at the same time.

I agree it would be better to have that option. I will see what I can modify from my code to make it behave as the expected later this week.

Cheers

**Comment by ZenithCode** [comment]
Thanks - that would be helpful.

**Comment by dkrprasetya** [comment]
Thank you for your suggestion. I have included this logic on [4f7f798](https://github.com/dkrprasetya/simple-firebase-unity/commit/4f7f7986ab58c43a90eed4a2da66f347102203c6).
